version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

workflows:
  run:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
        name: Install Python Dependencies
        command: |
          echo 'Installing dependencies'
          pip install --user -r requirements.txt
